### PyTorch Basics

In [1]:
import torch 
import numpy as np 

In [2]:

print(torch.cuda.is_available())  # Should return True if CUDA is ready
print(torch.cuda.get_device_name(0))  # Shows your GPU name


True
NVIDIA GeForce GTX 1050 Ti


In [3]:
def describe(x): 
    print("Type: {}".format(x.type())) 
    print("Shape/size: {}".format(x.shape)) 
    print("Values: \n{}".format(x))

In [4]:
describe(torch.Tensor(2,3))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[-1.0662e-14,  1.3032e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [5]:
#unifrom distribution
describe(torch.rand(2,3))
#gaussian distribution
describe(torch.randn(2,3))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.6550, 0.0432, 0.7949],
        [0.5079, 0.1900, 0.7931]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.9597,  0.2207, -2.7454],
        [ 1.6296,  0.7142,  0.1412]])


In [6]:
describe(torch.zeros(2,3))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
x = torch.ones(2,3)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [8]:
x.fill_(10)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[10., 10., 10.],
        [10., 10., 10.]])


## Creating Tensor from Lists

In [9]:
a = [[1,2,3],[4,5,6]]
a_tensor = torch.Tensor(a)
describe(a_tensor)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


## Types of Tensor 
1. Float Tensor (default)
2. Double Tensor
3. Long Tensor 

In [10]:
print(""" 
Tensor Type     Data Type	Precision	    Typical Use Case
FloatTensor	    float32	    32-bit float	Default for most neural networks
DoubleTensor	float64	    64-bit float	High-precision computations (e.g., scientific computing)
LongTensor	    int64	    64-bit integer  Indexing, counting, class labels
""")

 
Tensor Type     Data Type	Precision	    Typical Use Case
FloatTensor	    float32	    32-bit float	Default for most neural networks
DoubleTensor	float64	    64-bit float	High-precision computations (e.g., scientific computing)
LongTensor	    int64	    64-bit integer  Indexing, counting, class labels



In [11]:
npy = np.random.rand(2, 3) 
y = torch.from_numpy(npy)
describe(y)

Type: torch.DoubleTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.9242, 0.1716, 0.8424],
        [0.6260, 0.3167, 0.2625]], dtype=torch.float64)


In [12]:
y = y.float()
describe(y)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.9242, 0.1716, 0.8424],
        [0.6260, 0.3167, 0.2625]])


In [13]:
z = y.long()
describe(z)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 0, 0],
        [0, 0, 0]])


In [14]:
y.size()

torch.Size([2, 3])

In [15]:
y.shape

torch.Size([2, 3])

In [16]:
y.type()

'torch.FloatTensor'

## Tensor Operations

### Addition

In [17]:
x1= torch.rand(2,3)

In [18]:
x1

tensor([[0.5053, 0.8268, 0.1680],
        [0.0192, 0.1781, 0.5770]])

In [19]:
print("Addition using '+' operator\n",x1+x1)
print("Addition using .add() function\n",torch.add(x1,x1))

Addition using '+' operator
 tensor([[1.0107, 1.6536, 0.3361],
        [0.0383, 0.3562, 1.1540]])
Addition using .add() function
 tensor([[1.0107, 1.6536, 0.3361],
        [0.0383, 0.3562, 1.1540]])


In [20]:
#arange function in torch
x2 = torch.arange(6)
describe(x2)

Type: torch.LongTensor
Shape/size: torch.Size([6])
Values: 
tensor([0, 1, 2, 3, 4, 5])


In [21]:
x2 = x2.view(2,3)
describe(x2)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


### Sum along an axis, the dimension mentioned will be collapsed.

In [22]:
print("Sum Along an axis:",describe(x2.sum(dim = 0)))

Type: torch.LongTensor
Shape/size: torch.Size([3])
Values: 
tensor([3, 5, 7])
Sum Along an axis: None


In [23]:
print("Sum Along an axis:",describe(x2.sum(dim = 1)))

Type: torch.LongTensor
Shape/size: torch.Size([2])
Values: 
tensor([ 3, 12])
Sum Along an axis: None


### torch.sum(x, dim=0) has the same functionality as x2.sum(dim = 0)

torch.transpose(input, dim0, dim1)
* input: the tensor you want to transpose
* dim0, dim1: the two dimensions you want to swap

In [24]:
torch.transpose(x2,0,1)

tensor([[0, 3],
        [1, 4],
        [2, 5]])

### Slicing and Indexing

In [25]:
x3 = torch.arange(12).view(3,4)
describe(x3)

Type: torch.LongTensor
Shape/size: torch.Size([3, 4])
Values: 
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [26]:
x3[:2,:3]

tensor([[0, 1, 2],
        [4, 5, 6]])

In [27]:
x3[2,3]

tensor(11)

### Complete Indexing
* index: When using index select, the index should be a Long Tensor
* dim: along which dim are we going to view the values. For a 2D Tensor dim = 0 allows to view the data along the row and dim = 1, allows to view the data along the column.

In [28]:
describe(x3)

Type: torch.LongTensor
Shape/size: torch.Size([3, 4])
Values: 
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [29]:
idx = torch.LongTensor([2,1])
torch.index_select(x3,dim = 1, index= idx)

tensor([[ 2,  1],
        [ 6,  5],
        [10,  9]])

In [30]:
idx = torch.LongTensor([1,0])
torch.index_select(x3,dim = 0, index= idx) 

tensor([[4, 5, 6, 7],
        [0, 1, 2, 3]])

In [31]:
row_indices = torch.arange(2).long() 
col_indices = torch.LongTensor([0, 1]) 
# describe(x[row_indices, col_indices])

In [32]:
#describe(x3[[0,2],[0,1]])

### Concate

In [33]:
describe(x3)

Type: torch.LongTensor
Shape/size: torch.Size([3, 4])
Values: 
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [34]:
describe(torch.cat([x3,x3], dim = 0))

Type: torch.LongTensor
Shape/size: torch.Size([6, 4])
Values: 
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [35]:
describe(torch.cat([x3,x3], dim = 1))

Type: torch.LongTensor
Shape/size: torch.Size([3, 8])
Values: 
tensor([[ 0,  1,  2,  3,  0,  1,  2,  3],
        [ 4,  5,  6,  7,  4,  5,  6,  7],
        [ 8,  9, 10, 11,  8,  9, 10, 11]])


## Cuda Settings

In [39]:
print(torch.cuda.is_available())

True


In [40]:
device = torch.device("cuda" if torch.cuda.is_available() else 
"cpu") 

In [41]:
print(device)

cuda


In [44]:
x5 = torch.rand(3,3).to(device)
describe(x5)

Type: torch.cuda.FloatTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[0.0560, 0.3687, 0.4476],
        [0.4043, 0.5082, 0.2154],
        [0.1325, 0.7794, 0.7888]], device='cuda:0')


In [45]:
torch.cuda.get_device_name()

'NVIDIA GeForce GTX 1050 Ti'

## Questions
 1. Create a 2D tensor and then add a dimension of size 1 inserted at dimension 0.
 2. Remove the extra dimension you just added to the previous tensor.
 3. Create a random tensor of shape 5x3 in the interval [3, 7).
 4. Create a tensor with values from a normal distribution (mean= 0 , std= 1).
 5. Retrieve the indexes of all the nonzero elements in the tensor torch.Tensor([1, 1, 1, 0, 1]).
 6. Create a random tensor of size (3,1) and then horizontally stack four copies together.
 7. Return the batch matrix-matrix product of two three-dimensional matrices (a=torch.rand(3,4,5), b=torch.rand(3,5,4))
 8. Return the batch matrix-matrix product of a 3D matrix and a 2D matrix (a=torch.rand(3,4,5), b=torch.rand(5,4))
 

In [47]:
##Ans1:
a1 = torch.arange(6).view(2,3)
describe(a1)
a1a = a1.view(1,2,3)
describe(a1a)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])
Type: torch.LongTensor
Shape/size: torch.Size([1, 2, 3])
Values: 
tensor([[[0, 1, 2],
         [3, 4, 5]]])


In [48]:
##Ans2:
a2 = a1a.view(2,3)
describe(a2)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [65]:
##Ans3:
a3 = torch.rand(2,3)*(7-3)+3
describe(a3)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[5.1295, 5.2754, 6.3538],
        [6.9314, 3.4263, 5.7014]])


In [51]:
##Ans4: 
a4 = torch.randn(2,3)
describe(a4)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 1.1901,  0.2761,  0.4381],
        [ 0.5397,  0.9984, -0.2068]])


In [56]:
##Ans5:
a5 = torch.LongTensor([1, 1, 1, 0, 1])
describe(a5)
describe(a5[a5>0])

Type: torch.LongTensor
Shape/size: torch.Size([5])
Values: 
tensor([1, 1, 1, 0, 1])
Type: torch.LongTensor
Shape/size: torch.Size([4])
Values: 
tensor([1, 1, 1, 1])


In [ ]:
#Ans6:
a6 = torch.rand(3,1)
cat = a6.clone().detach()
for i in range(3):
    cat = torch.cat([cat,a6],dim=0)

describe(cat)

Type: torch.FloatTensor
Shape/size: torch.Size([12, 1])
Values: 
tensor([[0.4538],
        [0.3271],
        [0.5355],
        [0.4538],
        [0.3271],
        [0.5355],
        [0.4538],
        [0.3271],
        [0.5355],
        [0.4538],
        [0.3271],
        [0.5355]])


In [61]:
##Ans7:
a7,b7 = torch.rand(3,4,5),torch.rand(3,5,4)
describe(torch.matmul(a7,b7))

Type: torch.FloatTensor
Shape/size: torch.Size([3, 4, 4])
Values: 
tensor([[[1.4940, 1.1239, 1.1427, 1.4468],
         [2.1868, 1.1232, 1.2509, 1.9576],
         [1.3149, 0.9936, 0.8907, 1.2354],
         [1.6106, 0.8312, 0.9712, 1.3305]],

        [[0.3653, 0.9853, 1.0858, 0.6550],
         [0.4704, 1.1231, 1.0685, 0.7730],
         [0.7031, 1.4670, 1.3065, 0.9318],
         [0.5188, 1.6170, 1.4924, 1.0577]],

        [[2.1454, 0.9253, 1.7265, 2.0386],
         [2.3770, 1.3541, 1.3021, 2.4219],
         [2.1538, 0.9455, 1.3759, 2.0571],
         [2.6032, 1.7448, 1.6913, 2.5821]]])


In [62]:
describe(torch.bmm(a7,b7))

Type: torch.FloatTensor
Shape/size: torch.Size([3, 4, 4])
Values: 
tensor([[[1.4940, 1.1239, 1.1427, 1.4468],
         [2.1868, 1.1232, 1.2509, 1.9576],
         [1.3149, 0.9936, 0.8907, 1.2354],
         [1.6106, 0.8312, 0.9712, 1.3305]],

        [[0.3653, 0.9853, 1.0858, 0.6550],
         [0.4704, 1.1231, 1.0685, 0.7730],
         [0.7031, 1.4670, 1.3065, 0.9318],
         [0.5188, 1.6170, 1.4924, 1.0577]],

        [[2.1454, 0.9253, 1.7265, 2.0386],
         [2.3770, 1.3541, 1.3021, 2.4219],
         [2.1538, 0.9455, 1.3759, 2.0571],
         [2.6032, 1.7448, 1.6913, 2.5821]]])


In [63]:
a8,b8=torch.rand(3,4,5),torch.rand(5,4)
describe(torch.matmul(a8,b8))

Type: torch.FloatTensor
Shape/size: torch.Size([3, 4, 4])
Values: 
tensor([[[2.2881, 1.4826, 1.4948, 1.7989],
         [1.2160, 1.3203, 1.0756, 0.9257],
         [1.8002, 2.1476, 1.4071, 1.6179],
         [1.5417, 1.4327, 1.4306, 1.1533]],

        [[0.8819, 0.7637, 0.8613, 0.6152],
         [1.5547, 1.2249, 0.8202, 1.2621],
         [2.1411, 0.8141, 1.5362, 1.4698],
         [2.0719, 1.4371, 1.1488, 1.6029]],

        [[1.8054, 1.1379, 1.2275, 1.3828],
         [1.3373, 0.7909, 1.0236, 0.9449],
         [1.3085, 0.7281, 0.9362, 1.0279],
         [1.7892, 1.2128, 1.0737, 1.4911]]])
